# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Quattro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Quattro
  pod 'Firebase/Core'  
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    # Add any other subspecs you want to use in your project
  ]

  target 'QuattroTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Quattro-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Quattro-tvOS

  target 'Quattro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
